export const PAQUETE_LIST_REQUEST = "PAQUETE_LIST_REQUEST";
export const PAQUETE_LIST_SUCCESS = "PAQUETE_LIST_SUCCESS";
export const PAQUETE_LIST_FAIL = "PAQUETE_LIST_FAIL";

export const PAQUETE_DETAILS_REQUEST = "PAQUETE_DETAILS_REQUEST";
export const PAQUETE_DETAILS_SUCCESS = "PAQUETE_DETAILS_SUCCESS";
export const PAQUETE_DETAILS_FAIL = "PAQUETE_DETAILS_FAIL";

export const PAQUETE_SAVE_REQUEST = "PAQUETE_SAVE_REQUEST";
export const PAQUETE_SAVE_SUCCESS = "PAQUETE_SAVE_SUCCESS";
export const PAQUETE_SAVE_FAIL = "PAQUETE_SAVE_FAIL";

export const PAQUETE_DELETE_REQUEST = "PAQUETE_DELETE_REQUEST";
export const PAQUETE_DELETE_SUCCESS = "PAQUETE_DELETE_SUCCESS";
export const PAQUETE_DELETE_FAIL = "PAQUETE_DELETE_FAIL";

export const PRODUCT_REVIEW_SAVE_REQUEST = "PRODUCT_REVIEW_SAVE_REQUEST";
export const PRODUCT_REVIEW_SAVE_SUCCESS = "PRODUCT_REVIEW_SAVE_SUCCESS";
export const PRODUCT_REVIEW_SAVE_FAIL = "PRODUCT_REVIEW_SAVE_FAIL";
export const PRODUCT_REVIEW_SAVE_RESET = "PRODUCT_REVIEW_SAVE_RESET";
